os:
  - linux
  - osx

addons:
  apt:
    packages:
      - nmap

language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install nmap; fi
