os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - nmap
  homebrew:
    packages:
      - nmap
    update: true

language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install nmap; fi
  - if [[ $TRAVIS_OS_NAME" == "windows"]]; then choco install nmap; fi