addons:
  apt:
    packages:
      - nmap
  homebrew:
    packages:
      - nmap
    update: true

language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"

jobs:
  include:
    - os: linux
    - os: osx
    - os: windows
      before_install:
        - choco install nmap
        - PowerShell $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User");
