os:
  - linux
  - osx

addons:
  apt:
    packages:
      - nmap

language: node_js

env:
  - NODE_VERSION="v4.6.2"
  - NODE_VERSION="v5.12.0"
  - NODE_VERSION="v6.9.1"
  - NODE_VERSION="v7.1.0"

node_js:
  - "node"
  - "iojs"
  - "lts/*"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install nvm; git clone https://github.com/creationix/nvm.git /tmp/.nvm; source /tmp/.nvm/nvm.sh; nvm install $NODE_VERSION; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install nmap; npm install; npm test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y nmap; nvm install $NODE_VERSION; npm install; npm test; fi

